### ISSUE TITLE
RuntimeError: Unable to locate turbojpeg library automatically

### ISSUE THREAD

**Issue by davidrapan** [home-assistant/actions#116]
I'm getting `RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.` during `Run home-assistant/actions/hassfest@master`, is that normal?

Full log w/ the error:
```
Run home-assistant/actions/hassfest@master
Run echo "::add-matcher::/home/runner/work/_actions/home-assistant/actions/master/hassfest/problem-matcher.json"
  echo "::add-matcher::/home/runner/work/_actions/home-assistant/actions/master/hassfest/problem-matcher.json"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Run docker run --rm -v /home/runner/work/ha-solarman/ha-solarman://github/workspace ghcr.io/home-assistant/hassfest
  docker run --rm -v /home/runner/work/ha-solarman/ha-solarman://github/workspace ghcr.io/home-assistant/hassfest
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Unable to find image 'ghcr.io/home-assistant/hassfest:latest' locally
latest: Pulling from home-assistant/hassfest
da9db07[2](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:3)f522: Already exists
96bad37e6db9: Pulling fs layer
e91fb7730f44: Pulling fs layer
a9059bd6473e: Pulling fs layer
d[3](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:4)89a8d584ef: Pulling fs layer
19892608c6ca: Pulling fs layer
a759110ce3e3: Pulling fs layer
19892608c6ca: Waiting
a759110ce3e3: Waiting
d389a8d58[4](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:5)ef: Waiting
a9059bd6473e: Verifying Checksum
a9059bd6473e: Download complete
96bad37e6db9: Download complete
d389a8d[5](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:7)84ef: Verifying Checksum
d389a8d584ef: Download complete
e91fb7730f44: Verifying Checksum
e91fb7730f44: Download complete
19892[6](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:8)08c6ca: Verifying Checksum
19892608c6ca: Download complete
96bad37e6db9: Pull complete
a759110ce3e3: Verifying Checksum
a[7](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:9)59110ce3e3: Download complete
e91fb7730f44: Pull complete
a9059bd6473e: Pull complete
d3[8](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:11)9a8d584ef: Pull complete
19892608c6ca: Pull complete
a759110ce3e3: Pull complete
Digest: sha256:44fd658ad14c0e[9](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:12)95e294a97c22f9cc3e10752f02cfabe467c276044a899209e
Status: Downloaded newer image for ghcr.io/home-assistant/hassfest:latest
Error loading libturbojpeg; Camera snapshot performance will be sub-optimal
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/camera/img_util.py", line [10](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:13)0, in __init__
    TurboJPEGSingleton.__instance = TurboJPEG()
                                    ~~~~~~~~~^^
  File "/usr/local/lib/python3.[13](https://github.com/davidrapan/ha-solarman/actions/runs/12215649659/job/34077850182#step:3:16)/site-packages/turbojpeg.py", line 300, in __init__
    self.__find_turbojpeg() if lib_path is None else lib_path)
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/turbojpeg.py", line 967, in __find_turbojpeg
    raise RuntimeError(
    ...<2 lines>...
        'e.g. jpeg = TurboJPEG(lib_path)')
RuntimeError: Unable to locate turbojpeg library automatically. You may specify the turbojpeg library path manually.
e.g. jpeg = TurboJPEG(lib_path)
Validating application_credentials... done in 0.00s
Validating bluetooth... done in 0.00s
Validating codeowners... done in 0.00s
Validating config_schema... done in 0.00s
Validating dependencies... done in 0.10s
Validating dhcp... done in 0.00s
Validating icons... done in 0.00s
Validating json... done in 0.00s
Validating manifest... done in 0.00s
Validating mqtt... done in 0.00s
Validating quality_scale... done in 0.00s
Validating requirements... done in 0.00s
Validating services... done in 0.01s
Validating ssdp... done in 0.00s
Validating translations... done in 0.00s
Validating usb... done in 0.00s
Validating zeroconf... done in 0.00s
Validating config_flow... done in 0.00s

Integrations: 1
Invalid integrations: 0
```

**Comment by BottlecapDave** [comment]
I am also seeing this issue
