### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by RonnyWinkler** [home-assistant/actions#75]
Hi, I tried to validate my component and get this error:
```

Validating manifest... done in 0.00s
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
Validating mqtt... done in 0.00s
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/src/homeassistant/script/hassfest/__main__.py", line 235, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/script/hassfest/__main__.py", line 162, in main
    plugin.validate(integrations, config)
  File "/usr/src/homeassistant/script/hassfest/requirements.py", line 60, in validate
    validate_requirements_format(integration)
  File "/usr/src/homeassistant/script/hassfest/requirements.py", line 83, in validate_requirements_format
    for req in integration.requirements:
  File "/usr/src/homeassistant/script/hassfest/model.py", line 166, in requirements
    return self.manifest.get("requirements", [])
AttributeError: 'NoneType' object has no attribute 'get'
Validating requirements...
Error: Process completed with exit code 1.
```

Integration:
https://github.com/RonnyWinkler/homeassistant.homey

It makes no difference if "requirements": [] is set in the manifest or not.
How can I fix this? Thanks for help and suggestions.
Ronny

Edit: Please wait. I think I missed a comma in the mainfest. I'll try again now...

**Comment by RonnyWinkler** [comment]
Sorry, missed a commy in manifest. The error pointed on the line after.
